<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dheenathayalans-MacBook-Air.local" failures="3" tests="53" name="runner.testRunnerTest" time="15.954" errors="0" timestamp="2025-02-11T21:50:16 EST" skipped="0">
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.209"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.225">
    <failure message="1 expectation failed.
Expected status code &lt;400&gt; but was &lt;201&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <201>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at utils.apiHelper.validateStatusCode(apiHelper.java:222)
at stepDefinitions.createUserStepDefinition.admin_receives_status_with_error_message(createUserStepDefinition.java:269)
at ✽.Admin receives "400" "Bad Request" Status with error message(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/2025_Team04_RestAssured_BDD/src/test/resources/features/02_createUser.feature:149)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.106"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.217"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.216"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.206"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.289"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.364"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.198"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.105"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.202"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.338"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.203"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.192"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.220"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.221"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.310"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.284"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.101"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.196"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.198"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.103"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.204"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.233"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.209"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="4.228"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.211"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.200"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.361"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.209"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.303"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.217"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.216"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.289"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.209"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.209"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.215"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.203"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.297"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.214">
    <failure message="1 expectation failed.
Expected status code &lt;201&gt; but was &lt;500&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <500>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at utils.apiHelper.validateStatusCode(apiHelper.java:222)
at stepDefinitions.createUserStepDefinition.admin_receives_status_for_create_user_mandatory(createUserStepDefinition.java:55)
at ✽.Admin receives "201" "Created" Status for create user mandatory(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/2025_Team04_RestAssured_BDD/src/test/resources/features/02_createUser.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.105"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.095"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.205">
    <failure message="1 expectation failed.
Expected status code &lt;400&gt; but was &lt;409&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <409>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at utils.apiHelper.validateStatusCode(apiHelper.java:222)
at stepDefinitions.createUserStepDefinition.admin_receives_status_with_error_message(createUserStepDefinition.java:269)
at ✽.Admin receives "400" "Bad Request" Status with error message(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/2025_Team04_RestAssured_BDD/src/test/resources/features/02_createUser.feature:69)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.206"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.502"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.289"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.284"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.297"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.196"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.214"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.223"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.217"/>
  <testcase classname="runner.testRunnerTest" name="runScenario" time="0.191"/>
</testsuite> <!-- runner.testRunnerTest -->
